run:
  tests: true
  skip-dirs-use-default: true

linters:
  enable-all: true
  disable:
    - depguard
    - deadcode
    - scopelint
    - exhaustruct
    - exhaustivestruct
    - varnamelen
    - testpackage
    - goerr113
    - maligned
    - godox
    - paralleltest
    - gci
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - linters:
        - contextcheck
      path: app.go
      text: "Non-inherited new context, use function like `context.WithXXX` instead"

    - path: (.+)_test.go
      linters:
        - gosec
        - unparam
        - errorlint

# all available settings of specific linters
linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 30
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 10.0
  misspell:
    locale: US
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
