name: 'ci'

on:
  pull_request:

jobs:
  ci:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'

      - name: 'Set up Go'
        uses: 'actions/setup-go@v4'
        with:
          go-version: '1.19'

      - name: 'Run lint'
        uses: 'golangci/golangci-lint-action@v3'
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.52

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true

      - name: 'Test'
        run: 'go test -v ./...'
